name: COREWIND Morro Bay In Situ
weather: central_ca.pqt
service_equipment:
  - [ctv.yaml, 7]
  - cab.yaml
  - dsv.yaml
  - ahv.yaml
  - hlv.yaml
layout: morro_bay_9D_layout.csv
port_distance: 60  # 20/100 for West of Barra Island; 10 for Gran Canaria Island
inflation_rate: 0
workday_start: 6
workday_end: 22
start_year: 2002
end_year: 2021
project_capacity: 1200
