name: dinwoodie_base
library: /Users/rhammond/Documents/GitHub/wombat/library/dinwoodie
weather: alpha_ventus_weather_2002_2014.csv
service_equipment: [ctv1.yaml, ctv2.yaml, ctv3.yaml, fsv.yaml, hlv_1.yaml, hlv_2.yaml, hlv_3.yaml]
layout: layout.csv
inflation_rate: 0
fixed_costs: fixed_costs.yaml
workday_start: 7
workday_end: 19
start_year: 2003
end_year: 2012
project_capacity: 240
