name: dinwoodie_historic_weather_100pct_reduction
library: DINWOODIE
weather: alpha_ventus_weather_2002_2014.csv
service_equipment: [ctv1.yaml, ctv2.yaml, ctv3.yaml, fsv_requests.yaml, hlv_requests.yaml]
layout: layout_100pct_reduction.csv
inflation_rate: 0
fixed_costs: fixed_costs.yaml
workday_start: 7
workday_end: 19
start_year: 2004
end_year: 2011
project_capacity: 240
